### ISSUE TITLE
Unclear error when a page title is identical to that of the parent-id

### ISSUE THREAD

**Issue by feliksik** [zeldigas/text2confl#142]
With [confluence-publisher](https://confluence-publisher.atlassian.net/), I used to provide my root asciidoc-page as 'ancestor'. Not sure if this was the intention, but it works. This way, the ancestor is replaced by the root asciidoc page, instead of it being attached under it. 

Text2confl accepts a `parent-id` instead of `ancestor`. It seems like the text2confl managed pages will be attached as children to the `parent-id`. Thus the parent-id is not be overwritten, but managed manually.  

I'm not sure which of these approaches is the safest; but with text2confl, when one of the pages actually has the title of the existing parent-id, it tries to update them, but also provides it's own ID as the parent: 

```
PUT https://confluence.myorg.example.com/rest/api/content/439755396

{
  "type": "page",
  "title": "My Title",
  "ancestors": [
    {
      "id": "439755396"
    }
  ],
  "version": {
    "number": 3,
    "minorEdit": false,
    "message": "Automated upload by text2confl"
  }
}

```

Note how the id in the PUT URL and the body are the same. 

This fails with a vague error that cost me a lot of time to figure out: 

```
Exception in thread "main" java.lang.RuntimeException: Failed to update 439755396: {"statusCode":500,"message":"","reason":"Internal Server Error"}
	at com.github.zeldigas.confclient.ConfluenceClientImpl.performPageUpdate(ConfluenceClientImpl.kt:204)
```

Also, when a text2conf page as the same title as another page that is not under the same ancestor, weird stuff happens: the existing page if updated and moved into the uploaded tree. It is more likely that this is a mistake by the user, if this page is not originally under the parent page.

**Comment by zeldigas** [comment]
Hello, thank you for the report. I'll prepare a fix that will check for clash with parent ID title.

As for "stealing" pages that are not under parent - that's a good question if this user mistake or intention. I think it is usually the latter, but I can add some marker in upload logs to highlight such scenarios or a command line option to detect this and fail.

**Comment by feliksik** [comment]
Thanks, that sounds great. I made a separate report #144 to detail the "page stealing" issue, as I think the title is a poor identifier, and leads to bigger problems. I'd be happy to help fix this!

**Comment by feliksik** [comment]
I think the problem might be a bit more generic. 

```
.
└── space-1
    ├── non-parent
    │   └── file
    └── the-parent
        ├── product-a
        │   ├── leaf-a1
        │   └── leaf-a2
        └── product-b
            ├── leaf-b1
            └── leaf-b2
```

Imagine I have a space called `space-1`, and want `product-a` and `product-b` to deploy their own tree. It conceivable (question is whether it's nicely supportable) that I want to manage the pages `product-a` and their children under `the-parent`, but I do not want to steal pages from `product-b` -- even though they _are_ under `the-parent`. 

I don't immediately see a good solution here. But I suspect that instead of adding many features to address ad-hoc needs (which may become a confusing mess), it may be worth to carefully consider how this could be better addressed. I'm not sure about how much time and care you want to put in such product management questions, but I'm happy to have a talk with you to explore this, if you want.

**Comment by feliksik** [comment]
I only just discovered the [option to provide a tenant](https://github.com/zeldigas/text2confl/blob/master/docs/user-guide/multitenant.md), which actually helps in addressing this issue, although it could still be useful to preven stealing of pages that are not associated with a tenant.

**Comment by zeldigas** [comment]
@feliksik  Tenants are designed to allow you to use text2confl from multiple page sources (e.g. separate git repos with docs) and avoid pages removal and stealing during cleanup. For single source publications this will not help you unfortunately.

I'm planning to fix issue with parent title this weekend. 

As for detection of stealing pages in general - let's continue discussion in #144

**Comment by zeldigas** [comment]
@feliksik  it took a while to find time and fix this, but now  there will be dedicated error for this scenario. Available in `latest` docker image, will create new release soon to have it included in version
