### ISSUE TITLE
Feature request: shorthand for commonly used macros (e.g. JIRA)

### ISSUE THREAD

**Issue by artem-nefedov** [zeldigas/text2confl#20]
It would be convenient to have a simple way to write commonly used macros, especially JIRA macro, since I don't want to deal with plain html/xml. The way I see it is for some special notation to be expanded by the client, and converted into html/xml before being sent to the server.

Proposals for how it may look:

- Similar to already existing `[TOC]`, e.g. `[JIRA issue=ABC-123]`.
- Using code-blocks with some special notation at the start, similar to how RMarkdown does it. E.g. for inline case:
```
`m jira(issue=ABC-123)`
```
For non-inline blocks it may look different.

**Comment by zeldigas** [comment]
@artem-nefedov  what about the following notation: `[JIRA:ABC-123]`. If reference is not resolved than it's treated as jira key, if resolved - regular resolution works.
Example can be found here: https://github.com/zeldigas/text2confl/commit/67f3d08fc3b29db3113933bc80973b3ffc2b5d57#diff-33969f6cd33a4783a41c5c9b21fad42b1e27df2650b8dff8c8a6f52b9fe4f7ec

**Comment by artem-nefedov** [comment]
That looks ok, but it's a little bit weird that format is different compared to TOC.
Also, this covers inline macro, but what about block jira tables?

**Comment by zeldigas** [comment]
It is targeting only to single issue scenario, i.e. for referring to jira issue in paragraph/other block. Jira table is usually used on it's own paragraph and frankly speaking I did not target it at all.

Alternative that i can think ofbased on you original proposal:

* `[JIRA jqlQuery="project = ABC" columns=key,summary,assignee,reporter,status maximumIssues=20]` for jira tables
* `[JIRA key=ABC-123]` for single issues

It is more consistent and same styled, but a bit more verbose for single issue scenario. What do you think?

**Comment by artem-nefedov** [comment]
I like the idea of keeping format consistent for everything, and laying a groundwork for the future, considering that you may add more macros and some of them (even inline ones) may take more than 1 parameter.

**Comment by zeldigas** [comment]
OK, I'll update change to this format. Indeed it looks promising for other macros

**Comment by zeldigas** [comment]
Released in 0.5.0
