### ISSUE TITLE
Tool is not working if a path to it has spaces in it

### ISSUE THREAD

**Issue by Broklya** [zeldigas/text2confl#26]
If a path to the distro of the tool has spaces in it, tool is not working

E.g. path: `C:\Program Files\text2confl-0.8.0-dist\text2confl`
Error code: `Error: Could not find or load main class Files\text2confl-0.8.0-dist\text2confl\app\*;C:\Program
Caused by: java.lang.ClassNotFoundException: Files\text2confl-0/8/0-dist\text2confl\app\*;C:\Program`

**Comment by zeldigas** [comment]
@Broklya please try https://github.com/zeldigas/text2confl/actions/runs/4976912235 build
